@echo off
mkdir backend\src\agents
mkdir backend\src\api
mkdir backend\src\services
mkdir backend\src\models
mkdir backend\src\schemas
mkdir backend\src\utils
mkdir backend\config
mkdir frontend\src\components
mkdir frontend\src\pages
mkdir frontend\src\utils
mkdir frontend\src\hooks
mkdir frontend\src\context
mkdir frontend\public\resources\agent-icons
mkdir frontend\public\resources\avatars
mkdir .github\workflows
echo 目录创建完成！